version: "3"

services:
  client:
    build: ./client
    stdin_open: true
    tty: true
    # command: npm run dev
    environment:
      VITE_BACKEND_URL: http://localhost:8080
    volumes:
      - ./client:/app
    ports:
      - 5173:5173
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: organization_management_system_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    # command: go run server.go
    volumes:
      - ./server:/go/src
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
  s3:
    image: quay.io/minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./.data/minio/data:/export
      - ./.data/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
    command: server /export --console-address ":9001"
  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://s3:9000 minioadmin minioadmin123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc alias set myminio http://s3:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/study-app-local;
      /usr/bin/mc anonymous set public myminio/study-app-local;
      /usr/bin/mc policy download myminio/study-app-local;
      exit 0;
      "
volumes:
  mysql_data:
