// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewVersion struct {
	Name      string    `json:"name"`
	StartedAt time.Time `json:"startedAt"`
}

type Todo struct {
	ID   uint   `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   uint   `json:"id"`
	Name string `json:"name"`
}
